ingress:
  className: "test"
  host: k8s-test.ontopic.dev
  tls: true
  secretName: ontopic-studio-tls
  annotations: {
    "kubernetes.io/ingress.class": "traefik",
    "cert-manager.io/cluster-issuer": "letsencrypt-staging",
  }

process-server:
  secrets:
    user-license-file: /run/secrets/user-license

store-server:
  env:
    database_host: store-server-db-postgresql.ontopic.svc.cluster.local
    database_port: 5432
    database_name: internal
    database_user: postgres
    casbin_store_host: store-server-db-postgresql.ontopic.svc.cluster.local
    casbin_store_port: 5432
    casbin_store_user: postgres
    ontop_endpoint_host: http://ontop-endpoint.ontopic.svc.cluster.local:8080
  secrets:
    database-password-file: /run/secrets/database-password-file

web:
  env:
    ONTOP_ENDPOINT_SERVICE_HOST: ontop-endpoint.ontopic.svc.cluster.local
    # virtual_host: ontopicosse.local

# identity-service:
#   secrets:
#     client-secret: /run/secrets/client-secret
#     cookie-secret: /run/secrets/cookie-secret
#     azure-api-client-secret: /run/secrets/azure-api-client-secret
#     okta-ssws-token: /run/secrets/okta-ssws-token
#     keycloak-admin-password-file: /run/secrets/keycloak-admin-password-file
#     identity-password-db: /run/secrets/password-file-db